import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {ReactQueryProvider} from "@/components/ReactQueryProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Dũng Vũ",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="mdl-js">
    <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
    <ReactQueryProvider>
      {children}
    </ReactQueryProvider>
    </body>
    </html>
  );
}
